site_name: CarteiraControl


theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  # logo: "icon-640.png"
  # favicon: "favicon-640.png"
  palette:
    primary: black
    accent: 146C94
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: #191717
      accent: #8ECDDD
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: #191717
      accent: #8ECDDD
  font:
    text: Roboto
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky

nav:
  - Início: index.md
  - Gunther's: historia.md
  - Visão Geral do Produto: VisaoProduto.md
  - Visão Geral do Projeto: VisaoProjeto.md
  - Processo de desenvolvimento: ProcessoDesenvolvimento.md
  - Lições aprendidas: Licoes.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

custom_css: 
  -custom/custom.css
