site_name: CarteiraControl


theme:
  name: material
  palette:
    primary: black
    accent: 146C94
  font:
    text: Roboto
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking

nav:
  - Início: index.md
  - Gunther's: historia.md
  - Visão Geral do Produto: VisaoProduto.md
  - Visão Geral do Projeto: VisaoProjeto.md
  - Processo de desenvolvimento: ProcessoDesenvolvimento.md
  - Lições aprendidas: Licoes.md

markdown_extensions:
  - attr_list
  - md_in_html

custom_css: 
  -custom/custom.css
