site_name: CarteiraControl

repo_url: https://github.com/mdsreq-fga-unb/2023.2-CarteiraControl
repo_name: CarteiraControl

docs_dir: docs
theme:
  name: material
  palette:
    primary: black
    accent: teal
  font:
    text: Roboto
  language: pt
nav:
  - Início: index.md
  - Gunther's: historia.md
  - Visão Geral do Produto: VisaoProduto.md
  - Visão Geral do Projeto: VisaoProjeto.md
  - Processo de desenvolvimento: ProcessoDesenvolvimento.md
  - Lições aprendidas: Licoes.md

markdown_extensions:
  - attr_list
  - md_in_html